### ISSUE TITLE
Can not run the container not by root.

### ISSUE THREAD

**Issue by lcgogo** [glifio/filecoin-docker#24]
In the entrypoint.sh, a dir /root/.lotus is made causes the container must run by root.
However, I want to run the container under nobody:nogoup instead of root.
Is there any trick that I can run the container with other user?

**Comment by ArseniiPetrovich** [comment]
Hey, lcogo! Sorry for the delayed response. What I think you can do is to override the entrypoint script with just using the `lotus daemon` when launching the container.

**Comment by symanovich-a** [comment]
done with #37 PR
