### ISSUE TITLE
The snapshot

### ISSUE THREAD

**Issue by satonz** [glifio/filecoin-docker#38]
How to specify snapshot when starting with Docker

**Comment by symanovich-a** [comment]
@satonz i'm not sure, if this is possible. we use initcontainer with[ import snapshot](https://github.com/glifio/filecoin-docker/blob/a84bd869e30ed8c25bda666ba5d6c9712b8380fa/scripts/entrypoint#L53) part. you may try to run alternately docker containers with custom entrypoint key [-n](https://github.com/glifio/filecoin-docker/blob/a84bd869e30ed8c25bda666ba5d6c9712b8380fa/scripts/entrypoint#L30) and --env SNAPSHOTURL="https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car" and then run as usual with sync state

**Comment by rkandratsiuk** [comment]
Hi, @satonz 
`--env SNAPSHOTURL="https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car"`
look at README.md . We had update it
