### ISSUE TITLE
Volumes not mapping to Host

### ISSUE THREAD

**Issue by pankajy721** [glifio/filecoin-docker#43]
docker run --detach \
        --publish 1235:1235 \
        --name lotus \
        --restart always \
        **--volume /File-Coin/filecoin-docker/data:/root/.lotus \**
        glif/lotus:$(BRANCH)

Volume given in this command are not mapping. I am able to see data sync inside the  container but not synching in volumes mapped on the host (in above command)

Any thing i might be missing here ?

Thanks for your help

**Comment by Jafner** [comment]
Are you trying to map the host side of the to a root-level directory?
`/File-Coin/filecoin-docker/data`  
Did you mean to use `~/File-Coin/filecoin-docker/data` or `./File-Coin/filecoin-docker/data`?
(I've made that mistake a few times myself.)
