### ISSUE TITLE
Create example docker-compose.yml

### ISSUE THREAD

**Issue by Jafner** [glifio/filecoin-docker#45]
The current readme describes how to build the image and run it, but doesn't specify many of the simple pieces of information which would be useful to someone trying to put together a working install.
A reference `docker-compose.yml` would provide a clean way to illustrate the important parameters of a working install. 

What (if any) ports need to be exposed?

**Comment by Jafner** [comment]
To answer my own question:
Filecoin-docker needs the following ports (as stated in the dockerfile itself):
`1234/tcp` for API access
`1235/tcp` for P2P access

An example `docker-compose.yml` would still be useful.

**Comment by rkandratsiuk** [comment]
Hi, @Jafner 
Just added `docker-compose.yaml`

**Comment by Jafner** [comment]
Awesome! 
I suspect a case like mine is relatively common or I wouldn't bother asking.
My docker host doesn't have a lot of local storage, but it is connected to a large NAS. 
How would I edit the volumes so that the configuration files are stored locally, but the ledger and data are handled by the NAS?

**Comment by symanovich-a** [comment]
Hey @Jafner 
You may mount your NAS to local folder and use it as local folder.
