### ISSUE TITLE
Lotus: "API not running (no endpoint)"

### ISSUE THREAD

**Issue by ollyhdh** [glifio/filecoin-docker#47]
**What I did:**
I'm on Windows. Docker is working and I have a WSL2 machine as well. 
I pulled master branch from git, and inside a WSL2 machine ran "make build" and "make run" 
Container started and seems to be doing someting. Has been running for many hours, see attached log.
ran "docker exec -it <containerID> bash" to get a shell.

**The Problem:**
running most lotus commands (version, sync status, sync wait) returns:
ERROR: could not get API info: could not get api endpoint: API not running (no endpoint)

_Note that the progress indicators like "23.24 GiB / 32.62 GiB 71.24% 1.65 MiB/s 1h36m52s" have already reached 100% at some point in my log, see somewhere in the middle._
Is this just supposed to run for even longer? and if so how do I find out the total progress?

**Other info:**
"lotus help" shows VERSION: 1.6.0-dev+mainnet+git.16965f1
"lotus wait-api" keeps saying:
   "Not online yet... (could not get API info: could not get api endpoint: API not running (no endpoint))"
I did not use any snapshot, and am not sure how I would even do that.

[2021-03-25 docker container log.zip](https://github.com/glifio/filecoin-docker/files/6207248/2021-03-25.docker.container.log.zip)

**Comment by symanovich-a** [comment]
hey @ollyhdh, could you try the latest image https://hub.docker.com/r/glif/lotus/tags ?
There are some steps to start lotus node:
- download full\lightweight  snapshot  https://docs.filecoin.io/get-started/lotus/chain/#lightweight-snapshot
- start syncing a gap between snapshot creation time and the current network status
Usually, you may see the different with command `lotus sync status` in the 2 step. if not - try see a list of lotus process `ps -x | grep [l]otus`
