### ISSUE TITLE
I have an error when i try to build in a windows docker

### ISSUE THREAD

**Issue by stradade** [glifio/filecoin-docker#48]
C:\filecoin-docker-master>docker-compose build
WARNING: The TAG variable is not set. Defaulting to a blank string.
WARNING: The HOME variable is not set. Defaulting to a blank string.
Building lotus
invalid argument "glif/lotus:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
ERROR: Service 'lotus' failed to build

**Comment by symanovich-a** [comment]
Hi @stradade,
It looks like you didn't set up variables TAG, HOME directory. Try in CMD _`setx TAG "master"`_ and _`setx HOME "somepath/lotus"`_ and open new CMD session and try `docker-compose build`
We haven't checked on win and i'm not sure in possibility to build on this platform before full docker native support, but as a variant - install virtual machine ubuntu and try in it.
