### ISSUE TITLE
lotus-miner connect error?

### ISSUE THREAD

**Issue by yangmiok** [glifio/filecoin-docker#53]
I run lotus ok in docker, docker ps like below:
`1f9fc8e3c272   glif/lotus:v1.9.0-dev   "/etc/lotus/docker/r…"   2 days ago   Up 47 hours   0.0.0.0:1234-1235->1234-1235/tcp, :::1234-1235->1234-1235/tcp   fil
ecoin-docker_lotus_1`

then the miner connect the lotus fail
`ERROR: websocket: bad handshake`

why,how to deal with it?

**Comment by symanovich-a** [comment]
HI @yangmiok, this is duplicate from slack chat.
```
"what is the scheme of connection lotus-miner -> lotus node? how do you publish port outside docker or miner and node in the same docker network?
Could you send export FULLNODE_API_INFO=<api_token>:/ip4/<lotus_daemon_ip>/tcp/<lotus_daemon_port> without api_token?"
```

**Comment by yangmiok** [comment]
the lotus and the miner in  different machines

**Comment by symanovich-a** [comment]
Is it accessible  port on lotus machine from miner machine?

**Comment by yangmiok** [comment]
yes, the port is ok

**Comment by yangmiok** [comment]
and I run:
`curl -X POST \
-H "Content-Type: application/json" \
--data '{
    "jsonrpc": "2.0",
    "method": "Filecoin.SyncState",
    "params": [],
    "id": 1
  }' \
  http://192.168.1.238:1234/rpc/v0`
from miner machine ,it is ok

**Comment by symanovich-a** [comment]
How do you apply FULLNODE_API_INFO variable?
Do you use systemd lotus-miner service? Could you show it?

**Comment by yangmiok** [comment]
`export FULLNODE_API_INFO=/ip4/192.168.1.238/tcp/1234/http`

**Comment by symanovich-a** [comment]
Try to use `/ip4/192.168.1.238/tcp/1234/rpc/v0` or `/ip4/192.168.1.238/tcp/1234`

**Comment by symanovich-a** [comment]
@yangmiok any updates?
