### ISSUE TITLE
Add calibration testnet.

### ISSUE THREAD

**Issue by vae520283995** [glifio/filecoin-docker#55]
Now only the mainnet

**Comment by symanovich-a** [comment]
hi @vae520283995,
You may change variable or use our [images ](https://hub.docker.com/r/glif/lotus/tags?page=1&ordering=last_updated)
`make -e NETWORK=calibnet build`

**Comment by vae520283995** [comment]
> hi @vae520283995,
> You may change variable or use our [images ](https://hub.docker.com/r/glif/lotus/tags?page=1&ordering=last_updated)
> `make -e NETWORK=calibnet build`

Thank you, does calibnet have SNAPSHOTURL?

**Comment by symanovich-a** [comment]
> > hi @vae520283995,
> > You may change variable or use our [images ](https://hub.docker.com/r/glif/lotus/tags?page=1&ordering=last_updated)
> > `make -e NETWORK=calibnet build`
> 
> Thank you, does calibnet have SNAPSHOTURL?

nope

**Comment by symanovich-a** [comment]
> > hi @vae520283995,
> > You may change variable or use our [images ](https://hub.docker.com/r/glif/lotus/tags?page=1&ordering=last_updated)
> > `make -e NETWORK=calibnet build`
> 
> Thank you, does calibnet have SNAPSHOTURL?

updated readme

**Comment by vae520283995** [comment]
```
docker run -d --name lotus \
   -p 1234:1234 -p 1235:1235 \
   -e NETWORK=calibnet \
   -e INFRA_LOTUS_DAEMON="true" \
   -e INFRA_LOTUS_HOME="/home/lotus_user" \
   -e INFRA_SYNC="true" \
   --network host \
   -v /tmp/lotus:/home/lotus_user \
  glif/lotus:v1.10.0
```
@symanovich-a 
It doesn't seem to work to specify this way, I started the mainnet

**Comment by vae520283995** [comment]
If I want to access the api externally, I must change 
```
ListenAddress = "/ip4/127.0.0.1/tcp/1234/http"
```
to 
```
ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
```
 in config.toml, right?

**Comment by symanovich-a** [comment]
> If I want to access the api externally, I must change
> 
> ```
> ListenAddress = "/ip4/127.0.0.1/tcp/1234/http"
> ```
> 
> to
> 
> ```
> ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
> ```
> 
> in config.toml, right?

yes, example https://github.com/glifio/filecoin-docker/blob/master/config/config.toml
you may find information in slack channels or on official site.
