### ISSUE TITLE
Docker-compose buils creashed

### ISSUE THREAD

**Issue by hakimehmordadi** [glifio/filecoin-docker#57]
I used docker-compose build but it crashed and not build. Please take a look. I need more.

**Comment by hakimehmordadi** [comment]
Could you please answer me?

**Comment by symanovich-a** [comment]
Hi @hakimehmordadi
What is the command do you use? Could you add some logs with errors?

**Comment by hakimehmordadi** [comment]
Hello @symanovich-, thank you for your answer. We need to run lotus on docker as soon as possible, I would like to use this code.

According to documentation of this code first of all 1- I cloned the source code on my computer 2- I did all of these below
```
## Create folder
mkdir -p $HOME/lotus && sudo chown -R 2000:2000 $HOME/lotus
## Build the Docker image
docker-compose build
## Run the Docker container
docker-compose up -d
```

I got error when using <docker build> and the error message is :  lotus service can not create .
There is no longer message. I suggest  to do this process by yourself to see the steps and what happen.

Many thanks.

**Comment by symanovich-a** [comment]
What is the OS, docker version, docker-compose version?
Do you run commands inside filecoin-docker folder?

**Comment by hakimehmordadi** [comment]
//Kernel 18.09.6
    //Ubuntu 18.04.2 LTS
    //Docker 4.15.0

**Comment by hakimehmordadi** [comment]
![1](https://user-images.githubusercontent.com/31950758/129009453-e79328a0-d475-45c3-ab34-b4196d529ae0.png)

**Comment by symanovich-a** [comment]
I'm not familiar with your virtualization service, but according to logs you can't allocate port inside your virtual machine.

**Comment by hakimehmordadi** [comment]
Did you run the lotus node with docker before ? I mean do you ensure the code and configuration works well. If yes please let me know which branch. My company wants to up node very soon we have a plan but because of docker we couldn't. Thanks

**Comment by symanovich-a** [comment]
https://api.node.glif.io runs on container from this repository. You may try to start this configuration on ubuntu directly, i mean connect on virtual machine(ssh, ui), install docker, docker-compose and try nerpanet, because mainnet has ~30gb snapshot and it will longer download.

**Comment by hakimehmordadi** [comment]
We are exchange company, and we need all functionality of the exchange needs them. As I heared, nerpanet do not have all exchange functionalities. does it?

**Comment by symanovich-a** [comment]
Yes, api doesn't have full functionality, but in this case it doesn't matter. I just try to help with simple filecoin start in docker and next step will be start mainnet node. I think, the issue is in virtualization system and i asked to start lotus just inside virtual machine.

**Comment by hakimehmordadi** [comment]
Could you please give more elaboration when you say   virtualization system
please. How can I realize  the problem happens from the server. How can I
find it in this case? It is important to realize why problems happen.
Actually I could run and create the container on my local machine with
docker commands.

Also I will send you some logs, maybe they will help.

**Comment by hakimehmordadi** [comment]
![3](https://user-images.githubusercontent.com/31950758/129077353-ac967bef-e5fe-43f0-a705-80ecea409026.png)

**Comment by hakimehmordadi** [comment]
![configs](https://user-images.githubusercontent.com/31950758/129077538-3227aca4-8a7f-4c33-9653-2fbef679fe69.png)

**Comment by hakimehmordadi** [comment]
![4](https://user-images.githubusercontent.com/31950758/129077621-ad9e1bcb-39b4-4173-9d0a-079123acc898.png)

**Comment by sergey989** [comment]
> Actually I could run and create the container on my local machine with docker commands.

That's why i asked about your virtualization system\service(VS). Try to ask support about this case
> Could you please give more elaboration when you say virtualization system

What is the VS to start docker? I mean some system\service -> virtual server -> docker
In logs i don't see errors, only warn and info. As i see, you user 2 version docker-compose, we use 3. You built somewhere image *.filecoin:457db288 and try to use it. Do they(VS and image build server) have the same CPU family ? Sometimes this may be an issue and to resolve this, we build image at the same server type

**Comment by ArseniiPetrovich** [comment]
@hakimehmordadi Can we schedule a call with you, so we can go through the deployment process together and see where the error is? Because it works just perfect on our end. 
It also might be worth considering Glif endpoints for your exchange. We are not providing the public endpoints only, but private as well with functionality being not limited.

**Comment by hakimehmordadi** [comment]
Hello Arsenii,

Yes, It would be great. Really we need to help from your side. We put in a
lot of effort and time but It is not possible to solve it. Yes we need to
be private. We are exchanging.
My company has a plan for launching filecoin and we can not run code after
up to one week of effort. There are so many Blockchain but we just have a
problem with Filecoin.
Please set a call for today, any time. I'm waiting for your call.

Cheers,
Hakime

**Comment by hakimehmordadi** [comment]
It would be  12 PM in moscow time. I'll see you. Thanks alot.

Cheers,
Hakimeh

**Comment by hakimehmordadi** [comment]
And please let me know which platform do you will use for making a call?
Slack, Discord, ... ?

**Comment by ArseniiPetrovich** [comment]
12 PM Moscow time, correct. 
We are using google meet, I've attached the link above.

**Comment by hakimehmordadi** [comment]
Hello,

I just want to remind you about the google meet link :)

Thanks

**Comment by ArseniiPetrovich** [comment]
Discussed via the call. Please reopen if needed.

**Comment by hakimehmordadi** [comment]
Arsenii Petrovich


sergey_s,
I really appreciate both of you guys. Many thanks.

Cheers,
Golnar
